# ROOT DIRECTORIES
DATA_DIR: ./data/
file_name: paperswithtopic.csv


# PREPROCESS
MAX_LEN: 64
PAD: True
pre_embed: False
embed_dim: 128 # for word2vec


# DATALOADER
test_size: .2
batch_size: 32


# MODEL CONFIG
model_name: 'bertclassification'

num_class: 16
vocab_size: 30471 # as default
hidden_dim: 128 # for models
n_layers: 1
n_heads: 8


# TRAIN
optimizer: adam
scheduler: plateau
learning_rate: .001
weight_decay: .0
loss: mlml # Multi Label Margin Loss
start_epoch: 0
n_epochs: 100
early_patience: 20


# MISC
seed: 42
use_saved: True
return_everything: False


# DEBUG
partial: 1