DATA_DIR: ./data/
MAX_LEN: 64
PAD: true
PTH_DIR: ./models/20210606-1309_bertclassification
batch_size: 128
device: cuda:0
drop:
- methodology
early_patience: 10
embed_dim: 128
file_name: paperswithtopic.csv
hidden_dim: 256
learning_rate: 0.0001
loss: bce
model_name: bertclassification
n_epochs: 100
n_heads: 16
n_layers: 4
num_class: 15
optimizer: adam
pad_index: 0
partial: 1
pre_embed: false
return_everything: false
save_period: 1
scheduler: plateau
seed: 42
start_epoch: 0
test_size: 0.1
unk_index: 1
use_bert_embed: false
use_saved: true
vocab_size: 30562
weight_decay: 0.0
which_output: last_hidden_state
output_attentions: False